language: python
sudo: false
python:
  - "3.8"
env:
  - DJANGO_VERSION=3.2
  - DJANGO_VERSION=4.2
install:
  - pip install -e .
  - pip install -q Django~=$DJANGO_VERSION
  - pip install -rrequirements-dev.txt
  - pip install codecov
script:
  - make coverage
after_success:
  - codecov
